Fix issue #186
dominion-dev/dominion-ecs-java pull request #188
Opened 2023-12-16 13:30 UTC by endison1986

2023-12-17 16:53 UTC, enricostara requested changes
A minor fix requested in ClassIndex

2023-12-17 16:53 UTC, enricostara commented on dominion-ecs-engine/src/main/java/dev/dominion/ecs/engine/system/ClassIndex.java
> +            if (cache.getVolatile(currentIndex - 1) != newClass) {
like above

2023-12-17 16:53 UTC, enricostara commented on dominion-ecs-engine/src/main/java/dev/dominion/ecs/engine/system/ClassIndex.java
> +        if (index != 0 && cache.get(index - 1) == klass) {
like above

2023-12-17 16:53 UTC, enricostara commented on dominion-ecs-engine/src/main/java/dev/dominion/ecs/engine/system/ClassIndex.java
> +            return index;
like above

2023-12-17 16:53 UTC, enricostara commented on dominion-ecs-engine/src/main/java/dev/dominion/ecs/engine/system/ClassIndex.java
> +                cache.set(idx - 1, newClass);
We cache currentIndex without -1, we don't care about wasting a position if it helps readability

2023-12-18 01:34 UTC, endison1986 commented
sorry，I don’t quite understand the operation of review，If there is anything incorrect, please correct me 🥺
I add LIC header and optimize readability with new commit.

2023-12-21 22:20 UTC, enricostara approved these changes

2023-12-21 22:20 UTC, merged